sudo: false

language: go

go:
 - master

script:
 - go build -x -v
 - go test -race -coverprofile=coverage.txt -covermode=atomic -a -x -v ./...

notifications:
  email:
    recipients:
      - github@pablo.tools
 
after_success:
 - bash <(curl -s https://codecov.io/bash)
